### ISSUE TITLE
download_file function in ztp_helper.py failing to download large files in ztp_helper.py

### ISSUE THREAD

**Issue by mvshpavan** [ios-xr/iosxr-ztp-python#1]
DDTS CSCvk34890 is tracking the same

We are trying to upgrade the image using ztp.
·       The helper function(download_file) in ztp_helper.py is not able to download the image(1.2Gb).
·       Urlopen/read is being used to download the file which is probably failing to download the large files.

2018-07-11 01:33:37,948 - DebugZTPLogger - DEBUG - Downloading file cafy1.tar from URL:http://223.31.88.254/DC14-NCS5501-RP0/cafy1.tar
(Global VRF NS                 ) Wed Jul 11 01:33:42 UTC 2018: (pid 27432) (/pkg/bin/ztp.sh)                       : Waiting on config apply finish (waited 45 secs, will wait 4800 secs)
(Global VRF NS                 ) Wed Jul 11 01:33:47 UTC 2018: (pid 27432) (/pkg/bin/ztp.sh)                       : ZTP is applying config

(Global VRF NS                 ) Wed Jul 11 01:44:13 UTC 2018: (pid 27432) (/pkg/bin/ztp.sh)                       : Waiting on config apply finish (waited 676 secs, will wait 4800 secs)
(Global VRF NS                 ) Wed Jul 11 01:44:18 UTC 2018: (pid 27432) (/pkg/bin/ztp.sh)                       : ZTP is applying config
Traceback (most recent call last):
  File "/disk0:/ztp/customer/config.candidate", line 685, in <module>
    install_result = ztp_script.install_xr_add_activate(SERVER_URL_PACKAGES + ALL_RPMS)
  File "/disk0:/ztp/customer/config.candidate", line 264, in install_xr_add_activate
    output = self.download_file(package_url, destination_folder="/misc/app_host/scratch")
  File "/pkg/bin/ztp_helper.py", line 173, in download_file
    local_file.write(f.read())
IOError: [Errno 28] No space left on device

**Comment by akshshar** [comment]
Thanks for creating the issue @mvshpavan , I have marked it as an enhancement to add support for chunking while downloading large files.

**Comment by akshshar** [comment]
Issue taken care of using the pull request:  https://github.com/ios-xr/iosxr-ztp-python/pull/2. Closing.
